dist: trusty
sudo: false
language: cpp

addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2 #call the build system in that folder and pass it the param -j2